language: java
jdk:
  - oraclejdk8
env:
  - TERM=dumb
before_install:
  - chmod +x gradlew
script: gradle clean build check
after_success:
  - gradle jacocoTestReport coveralls
notifications:
  email: false
