/*
 * Copyright (c) 2015. Yutaka Kato. All rights reserved.
 * https://github.com/mikan/java8-training-course
 */

package local.js8ri.ch08.ex10;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Scanner;
import java.util.stream.Stream;

/**
 * Walk around src.zip.
 *
 * @author mikan
 */
public class SrcZipWalker {

    public static void main(String[] args) throws IOException {
        System.out.print("Path to top of extracted src.zip: ");
        Scanner scanner = new Scanner(System.in);
        String path = scanner.nextLine();
        find(Paths.get(path)).forEach(System.out::println);
    }

    private static Stream<Path> find(Path root) throws IOException {
        return Files.walk(root).filter(p -> p.toFile().isFile()).filter(p -> {
            try {
                return Files.readAllLines(p).stream().anyMatch(
                        s -> s.contains("transient") || s.contains("volatile"));
            } catch (IOException e) {
                System.err.println("IOE caught: " + e.getMessage());
                return false;
            }
        });
    }

    /*
    Result:

    Path to top of extracted src.zip: /Users/yutaka/Desktop/src
    /Users/yutaka/Desktop/src/com/sun/corba/se/impl/activation/RepositoryImpl.java
    /Users/yutaka/Desktop/src/com/sun/corba/se/impl/activation/ServerMain.java
    /Users/yutaka/Desktop/src/com/sun/corba/se/impl/encoding/CachedCodeBase.java
    /Users/yutaka/Desktop/src/com/sun/corba/se/impl/io/FVDCodeBaseImpl.java
    /Users/yutaka/Desktop/src/com/sun/corba/se/impl/io/IIOPInputStream.java
    /Users/yutaka/Desktop/src/com/sun/corba/se/impl/io/ObjectStreamClass.java
    /Users/yutaka/Desktop/src/com/sun/corba/se/impl/ior/ObjectReferenceFactoryImpl.java
    /Users/yutaka/Desktop/src/com/sun/corba/se/impl/ior/ObjectReferenceProducerBase.java
    /Users/yutaka/Desktop/src/com/sun/corba/se/impl/ior/ObjectReferenceTemplateImpl.java
    /Users/yutaka/Desktop/src/com/sun/corba/se/impl/logging/NamingSystemException.java
    /Users/yutaka/Desktop/src/com/sun/corba/se/impl/naming/cosnaming/NamingContextImpl.java
    /Users/yutaka/Desktop/src/com/sun/corba/se/impl/naming/cosnaming/TransientNameServer.java
    /Users/yutaka/Desktop/src/com/sun/corba/se/impl/naming/cosnaming/TransientNameService.java
    /Users/yutaka/Desktop/src/com/sun/corba/se/impl/naming/cosnaming/TransientNamingContext.java
    /Users/yutaka/Desktop/src/com/sun/corba/se/impl/naming/pcosnaming/InternalBindingValue.java
    /Users/yutaka/Desktop/src/com/sun/corba/se/impl/naming/pcosnaming/NameServer.java
    /Users/yutaka/Desktop/src/com/sun/corba/se/impl/naming/pcosnaming/NamingContextImpl.java
    /Users/yutaka/Desktop/src/com/sun/corba/se/impl/naming/pcosnaming/ServantManagerImpl.java
    /Users/yutaka/Desktop/src/com/sun/corba/se/impl/oa/toa/TOA.java
    /Users/yutaka/Desktop/src/com/sun/corba/se/impl/oa/toa/TOAImpl.java
    /Users/yutaka/Desktop/src/com/sun/corba/se/impl/oa/toa/TransientObjectManager.java
    /Users/yutaka/Desktop/src/com/sun/corba/se/impl/orb/ORBDataParserImpl.java
    /Users/yutaka/Desktop/src/com/sun/corba/se/impl/orb/ORBImpl.java
    /Users/yutaka/Desktop/src/com/sun/corba/se/impl/orb/ORBSingleton.java
    /Users/yutaka/Desktop/src/com/sun/corba/se/impl/orbutil/ObjectStreamClass_1_3_1.java
    /Users/yutaka/Desktop/src/com/sun/corba/se/impl/orbutil/ObjectStreamClassUtil_1_3.java
    /Users/yutaka/Desktop/src/com/sun/corba/se/impl/orbutil/threadpool/ThreadPoolImpl.java
    /Users/yutaka/Desktop/src/com/sun/corba/se/impl/presentation/rmi/InvocationHandlerFactoryImpl.java
    /Users/yutaka/Desktop/src/com/sun/corba/se/impl/presentation/rmi/StubInvocationHandlerImpl.java
    /Users/yutaka/Desktop/src/com/sun/corba/se/impl/transport/SelectorImpl.java
    /Users/yutaka/Desktop/src/com/sun/corba/se/impl/util/IdentityHashtable.java
    /Users/yutaka/Desktop/src/com/sun/corba/se/spi/legacy/connection/ORBSocketFactory.java
    /Users/yutaka/Desktop/src/com/sun/corba/se/spi/orb/ORB.java
    /Users/yutaka/Desktop/src/com/sun/corba/se/spi/orb/ORBData.java
    /Users/yutaka/Desktop/src/com/sun/java/swing/plaf/motif/MotifDesktopPaneUI.java
    /Users/yutaka/Desktop/src/com/sun/java/swing/plaf/windows/WindowsLookAndFeel.java
    /Users/yutaka/Desktop/src/com/sun/java/swing/plaf/windows/WindowsToggleButtonUI.java
    /Users/yutaka/Desktop/src/com/sun/javadoc/FieldDoc.java
    /Users/yutaka/Desktop/src/com/sun/jmx/interceptor/DefaultMBeanServerInterceptor.java
    /Users/yutaka/Desktop/src/com/sun/jmx/mbeanserver/JmxMBeanServer.java
    /Users/yutaka/Desktop/src/com/sun/jmx/mbeanserver/Repository.java
    /Users/yutaka/Desktop/src/com/sun/jmx/remote/internal/ClientCommunicatorAdmin.java
    /Users/yutaka/Desktop/src/com/sun/jmx/remote/internal/ClientNotifForwarder.java
    /Users/yutaka/Desktop/src/com/sun/jmx/snmp/agent/SnmpMib.java
    /Users/yutaka/Desktop/src/com/sun/jmx/snmp/agent/SnmpMibAgent.java
    /Users/yutaka/Desktop/src/com/sun/jmx/snmp/agent/SnmpMibTable.java
    /Users/yutaka/Desktop/src/com/sun/jmx/snmp/agent/SnmpUserDataFactory.java
    /Users/yutaka/Desktop/src/com/sun/jmx/snmp/daemon/CommunicatorServer.java
    /Users/yutaka/Desktop/src/com/sun/jmx/snmp/daemon/SnmpAdaptorServer.java
    /Users/yutaka/Desktop/src/com/sun/jmx/snmp/daemon/SnmpInformRequest.java
    /Users/yutaka/Desktop/src/com/sun/jmx/snmp/daemon/SnmpRequestHandler.java
    /Users/yutaka/Desktop/src/com/sun/jmx/snmp/daemon/SnmpSession.java
    /Users/yutaka/Desktop/src/com/sun/jmx/snmp/daemon/SnmpSocket.java
    /Users/yutaka/Desktop/src/com/sun/jmx/snmp/internal/SnmpEngineImpl.java
    /Users/yutaka/Desktop/src/com/sun/jmx/snmp/SnmpEngine.java
    /Users/yutaka/Desktop/src/com/sun/org/apache/bcel/internal/classfile/JavaClass.java
    /Users/yutaka/Desktop/src/com/sun/org/apache/bcel/internal/Constants.java
    /Users/yutaka/Desktop/src/com/sun/org/apache/regexp/internal/RE.java
    /Users/yutaka/Desktop/src/com/sun/org/apache/xalan/internal/utils/SecuritySupport.java
    /Users/yutaka/Desktop/src/com/sun/org/apache/xalan/internal/xsltc/runtime/Hashtable.java
    /Users/yutaka/Desktop/src/com/sun/org/apache/xalan/internal/xsltc/trax/TemplatesImpl.java
    /Users/yutaka/Desktop/src/com/sun/org/apache/xerces/internal/dom/AttrImpl.java
    /Users/yutaka/Desktop/src/com/sun/org/apache/xerces/internal/dom/CharacterDataImpl.java
    /Users/yutaka/Desktop/src/com/sun/org/apache/xerces/internal/dom/ChildNode.java
    /Users/yutaka/Desktop/src/com/sun/org/apache/xerces/internal/dom/CoreDocumentImpl.java
    /Users/yutaka/Desktop/src/com/sun/org/apache/xerces/internal/dom/DeferredAttrImpl.java
    /Users/yutaka/Desktop/src/com/sun/org/apache/xerces/internal/dom/DeferredAttrNSImpl.java
    /Users/yutaka/Desktop/src/com/sun/org/apache/xerces/internal/dom/DeferredCDATASectionImpl.java
    /Users/yutaka/Desktop/src/com/sun/org/apache/xerces/internal/dom/DeferredCommentImpl.java
    /Users/yutaka/Desktop/src/com/sun/org/apache/xerces/internal/dom/DeferredDocumentImpl.java
    /Users/yutaka/Desktop/src/com/sun/org/apache/xerces/internal/dom/DeferredDocumentTypeImpl.java
    /Users/yutaka/Desktop/src/com/sun/org/apache/xerces/internal/dom/DeferredElementDefinitionImpl.java
    /Users/yutaka/Desktop/src/com/sun/org/apache/xerces/internal/dom/DeferredElementImpl.java
    /Users/yutaka/Desktop/src/com/sun/org/apache/xerces/internal/dom/DeferredElementNSImpl.java
    /Users/yutaka/Desktop/src/com/sun/org/apache/xerces/internal/dom/DeferredEntityImpl.java
    /Users/yutaka/Desktop/src/com/sun/org/apache/xerces/internal/dom/DeferredEntityReferenceImpl.java
    /Users/yutaka/Desktop/src/com/sun/org/apache/xerces/internal/dom/DeferredNotationImpl.java
    /Users/yutaka/Desktop/src/com/sun/org/apache/xerces/internal/dom/DeferredProcessingInstructionImpl.java
    /Users/yutaka/Desktop/src/com/sun/org/apache/xerces/internal/dom/DeferredTextImpl.java
    /Users/yutaka/Desktop/src/com/sun/org/apache/xerces/internal/dom/DocumentImpl.java
    /Users/yutaka/Desktop/src/com/sun/org/apache/xerces/internal/dom/ElementNSImpl.java
    /Users/yutaka/Desktop/src/com/sun/org/apache/xerces/internal/dom/ParentNode.java
    /Users/yutaka/Desktop/src/com/sun/org/apache/xerces/internal/impl/dtd/models/DFAContentModel.java
    /Users/yutaka/Desktop/src/com/sun/org/apache/xerces/internal/impl/dv/xs/AbstractDateTimeDV.java
    /Users/yutaka/Desktop/src/com/sun/org/apache/xerces/internal/impl/XMLStreamReaderImpl.java
    /Users/yutaka/Desktop/src/com/sun/org/apache/xerces/internal/impl/xpath/regex/RegularExpression.java
    /Users/yutaka/Desktop/src/com/sun/org/apache/xerces/internal/impl/xs/models/XSDFACM.java
    /Users/yutaka/Desktop/src/com/sun/org/apache/xerces/internal/impl/xs/XSComplexTypeDecl.java
    /Users/yutaka/Desktop/src/com/sun/org/apache/xerces/internal/utils/SecuritySupport.java
    /Users/yutaka/Desktop/src/com/sun/org/apache/xerces/internal/xni/Augmentations.java
    /Users/yutaka/Desktop/src/com/sun/org/apache/xerces/internal/xni/XMLString.java
    /Users/yutaka/Desktop/src/com/sun/org/apache/xml/internal/dtm/ref/dom2dtm/DOM2DTM.java
    /Users/yutaka/Desktop/src/com/sun/org/apache/xml/internal/dtm/ref/sax2dtm/SAX2DTM.java
    /Users/yutaka/Desktop/src/com/sun/org/apache/xml/internal/security/utils/XMLUtils.java
    /Users/yutaka/Desktop/src/com/sun/org/apache/xml/internal/utils/ThreadControllerWrapper.java
    /Users/yutaka/Desktop/src/com/sun/org/apache/xpath/internal/axes/AxesWalker.java
    /Users/yutaka/Desktop/src/com/sun/org/apache/xpath/internal/axes/ChildTestIterator.java
    /Users/yutaka/Desktop/src/com/sun/org/apache/xpath/internal/axes/DescendantIterator.java
    /Users/yutaka/Desktop/src/com/sun/org/apache/xpath/internal/axes/FilterExprIterator.java
    /Users/yutaka/Desktop/src/com/sun/org/apache/xpath/internal/axes/FilterExprIteratorSimple.java
    /Users/yutaka/Desktop/src/com/sun/org/apache/xpath/internal/axes/FilterExprWalker.java
    /Users/yutaka/Desktop/src/com/sun/org/apache/xpath/internal/axes/LocPathIterator.java
    /Users/yutaka/Desktop/src/com/sun/org/apache/xpath/internal/axes/PredicatedNodeTest.java
    /Users/yutaka/Desktop/src/com/sun/org/apache/xpath/internal/compiler/XPathParser.java
    /Users/yutaka/Desktop/src/com/sun/org/apache/xpath/internal/functions/FuncExtFunctionAvailable.java
    /Users/yutaka/Desktop/src/com/sun/org/apache/xpath/internal/NodeSet.java
    /Users/yutaka/Desktop/src/com/sun/org/apache/xpath/internal/NodeSetDTM.java
    /Users/yutaka/Desktop/src/com/sun/org/apache/xpath/internal/XPath.java
    /Users/yutaka/Desktop/src/com/sun/security/auth/X500Principal.java
    /Users/yutaka/Desktop/src/java/applet/Applet.java
    /Users/yutaka/Desktop/src/java/awt/AWTEvent.java
    /Users/yutaka/Desktop/src/java/awt/Button.java
    /Users/yutaka/Desktop/src/java/awt/Checkbox.java
    /Users/yutaka/Desktop/src/java/awt/CheckboxMenuItem.java
    /Users/yutaka/Desktop/src/java/awt/Choice.java
    /Users/yutaka/Desktop/src/java/awt/color/ColorSpace.java
    /Users/yutaka/Desktop/src/java/awt/color/ICC_ColorSpace.java
    /Users/yutaka/Desktop/src/java/awt/color/ICC_Profile.java
    /Users/yutaka/Desktop/src/java/awt/Component.java
    /Users/yutaka/Desktop/src/java/awt/Container.java
    /Users/yutaka/Desktop/src/java/awt/ContainerOrderFocusTraversalPolicy.java
    /Users/yutaka/Desktop/src/java/awt/Cursor.java
    /Users/yutaka/Desktop/src/java/awt/datatransfer/DataFlavor.java
    /Users/yutaka/Desktop/src/java/awt/Dialog.java
    /Users/yutaka/Desktop/src/java/awt/dnd/DragGestureEvent.java
    /Users/yutaka/Desktop/src/java/awt/dnd/DragGestureRecognizer.java
    /Users/yutaka/Desktop/src/java/awt/dnd/DragSource.java
    /Users/yutaka/Desktop/src/java/awt/dnd/DragSourceContext.java
    /Users/yutaka/Desktop/src/java/awt/dnd/DropTarget.java
    /Users/yutaka/Desktop/src/java/awt/dnd/DropTargetContext.java
    /Users/yutaka/Desktop/src/java/awt/event/FocusEvent.java
    /Users/yutaka/Desktop/src/java/awt/event/InputEvent.java
    /Users/yutaka/Desktop/src/java/awt/event/InputMethodEvent.java
    /Users/yutaka/Desktop/src/java/awt/event/InvocationEvent.java
    /Users/yutaka/Desktop/src/java/awt/event/KeyEvent.java
    /Users/yutaka/Desktop/src/java/awt/event/MouseEvent.java
    /Users/yutaka/Desktop/src/java/awt/event/WindowEvent.java
    /Users/yutaka/Desktop/src/java/awt/Event.java
    /Users/yutaka/Desktop/src/java/awt/EventDispatchThread.java
    /Users/yutaka/Desktop/src/java/awt/EventQueue.java
    /Users/yutaka/Desktop/src/java/awt/font/FontRenderContext.java
    /Users/yutaka/Desktop/src/java/awt/font/NumericShaper.java
    /Users/yutaka/Desktop/src/java/awt/Font.java
    /Users/yutaka/Desktop/src/java/awt/Frame.java
    /Users/yutaka/Desktop/src/java/awt/geom/AffineTransform.java
    /Users/yutaka/Desktop/src/java/awt/geom/Path2D.java
    /Users/yutaka/Desktop/src/java/awt/GridBagConstraints.java
    /Users/yutaka/Desktop/src/java/awt/GridBagLayout.java
    /Users/yutaka/Desktop/src/java/awt/ImageCapabilities.java
    /Users/yutaka/Desktop/src/java/awt/KeyboardFocusManager.java
    /Users/yutaka/Desktop/src/java/awt/List.java
    /Users/yutaka/Desktop/src/java/awt/MenuBar.java
    /Users/yutaka/Desktop/src/java/awt/MenuComponent.java
    /Users/yutaka/Desktop/src/java/awt/MenuItem.java
    /Users/yutaka/Desktop/src/java/awt/peer/ComponentPeer.java
    /Users/yutaka/Desktop/src/java/awt/PopupMenu.java
    /Users/yutaka/Desktop/src/java/awt/Robot.java
    /Users/yutaka/Desktop/src/java/awt/Scrollbar.java
    /Users/yutaka/Desktop/src/java/awt/ScrollPaneAdjustable.java
    /Users/yutaka/Desktop/src/java/awt/SystemColor.java
    /Users/yutaka/Desktop/src/java/awt/SystemTray.java
    /Users/yutaka/Desktop/src/java/awt/TextComponent.java
    /Users/yutaka/Desktop/src/java/awt/TextField.java
    /Users/yutaka/Desktop/src/java/awt/Toolkit.java
    /Users/yutaka/Desktop/src/java/awt/TrayIcon.java
    /Users/yutaka/Desktop/src/java/awt/WaitDispatchSupport.java
    /Users/yutaka/Desktop/src/java/awt/Window.java
    /Users/yutaka/Desktop/src/java/beans/beancontext/BeanContextChild.java
    /Users/yutaka/Desktop/src/java/beans/beancontext/BeanContextChildSupport.java
    /Users/yutaka/Desktop/src/java/beans/beancontext/BeanContextServicesSupport.java
    /Users/yutaka/Desktop/src/java/beans/beancontext/BeanContextSupport.java
    /Users/yutaka/Desktop/src/java/beans/Beans.java
    /Users/yutaka/Desktop/src/java/beans/DefaultPersistenceDelegate.java
    /Users/yutaka/Desktop/src/java/beans/FeatureDescriptor.java
    /Users/yutaka/Desktop/src/java/beans/ThreadGroupContext.java
    /Users/yutaka/Desktop/src/java/beans/Transient.java
    /Users/yutaka/Desktop/src/java/beans/WeakIdentityMap.java
    /Users/yutaka/Desktop/src/java/io/BufferedInputStream.java
    /Users/yutaka/Desktop/src/java/io/File.java
    /Users/yutaka/Desktop/src/java/io/FileInputStream.java
    /Users/yutaka/Desktop/src/java/io/FileOutputStream.java
    /Users/yutaka/Desktop/src/java/io/FilePermission.java
    /Users/yutaka/Desktop/src/java/io/FilterInputStream.java
    /Users/yutaka/Desktop/src/java/io/ObjectInputStream.java
    /Users/yutaka/Desktop/src/java/io/ObjectOutputStream.java
    /Users/yutaka/Desktop/src/java/io/ObjectStreamClass.java
    /Users/yutaka/Desktop/src/java/io/PipedInputStream.java
    /Users/yutaka/Desktop/src/java/io/RandomAccessFile.java
    /Users/yutaka/Desktop/src/java/io/Serializable.java
    /Users/yutaka/Desktop/src/java/lang/Class.java
    /Users/yutaka/Desktop/src/java/lang/ClassValue.java
    /Users/yutaka/Desktop/src/java/lang/invoke/CallSite.java
    /Users/yutaka/Desktop/src/java/lang/invoke/MemberName.java
    /Users/yutaka/Desktop/src/java/lang/invoke/MutableCallSite.java
    /Users/yutaka/Desktop/src/java/lang/invoke/SwitchPoint.java
    /Users/yutaka/Desktop/src/java/lang/invoke/VolatileCallSite.java
    /Users/yutaka/Desktop/src/java/lang/Package.java
    /Users/yutaka/Desktop/src/java/lang/ref/Finalizer.java
    /Users/yutaka/Desktop/src/java/lang/ref/Reference.java
    /Users/yutaka/Desktop/src/java/lang/ref/ReferenceQueue.java
    /Users/yutaka/Desktop/src/java/lang/reflect/AccessibleObject.java
    /Users/yutaka/Desktop/src/java/lang/reflect/Constructor.java
    /Users/yutaka/Desktop/src/java/lang/reflect/Executable.java
    /Users/yutaka/Desktop/src/java/lang/reflect/Field.java
    /Users/yutaka/Desktop/src/java/lang/reflect/Method.java
    /Users/yutaka/Desktop/src/java/lang/reflect/Modifier.java
    /Users/yutaka/Desktop/src/java/lang/reflect/Parameter.java
    /Users/yutaka/Desktop/src/java/lang/StringBuffer.java
    /Users/yutaka/Desktop/src/java/lang/System.java
    /Users/yutaka/Desktop/src/java/lang/Thread.java
    /Users/yutaka/Desktop/src/java/lang/Throwable.java
    /Users/yutaka/Desktop/src/java/math/BigDecimal.java
    /Users/yutaka/Desktop/src/java/math/BigInteger.java
    /Users/yutaka/Desktop/src/java/net/Inet6Address.java
    /Users/yutaka/Desktop/src/java/net/InetAddress.java
    /Users/yutaka/Desktop/src/java/net/InetSocketAddress.java
    /Users/yutaka/Desktop/src/java/net/SocketPermission.java
    /Users/yutaka/Desktop/src/java/net/URI.java
    /Users/yutaka/Desktop/src/java/net/URL.java
    /Users/yutaka/Desktop/src/java/net/URLPermission.java
    /Users/yutaka/Desktop/src/java/nio/Bits.java
    /Users/yutaka/Desktop/src/java/nio/channels/SelectionKey.java
    /Users/yutaka/Desktop/src/java/nio/channels/spi/AbstractInterruptibleChannel.java
    /Users/yutaka/Desktop/src/java/nio/channels/spi/AbstractSelectionKey.java
    /Users/yutaka/Desktop/src/java/nio/charset/Charset.java
    /Users/yutaka/Desktop/src/java/nio/file/attribute/AclEntry.java
    /Users/yutaka/Desktop/src/java/nio/file/spi/FileSystemProvider.java
    /Users/yutaka/Desktop/src/java/rmi/activation/ActivationID.java
    /Users/yutaka/Desktop/src/java/rmi/server/RemoteObject.java
    /Users/yutaka/Desktop/src/java/security/BasicPermission.java
    /Users/yutaka/Desktop/src/java/security/cert/CertificateRevokedException.java
    /Users/yutaka/Desktop/src/java/security/cert/X509Certificate.java
    /Users/yutaka/Desktop/src/java/security/cert/X509CRL.java
    /Users/yutaka/Desktop/src/java/security/CodeSigner.java
    /Users/yutaka/Desktop/src/java/security/CodeSource.java
    /Users/yutaka/Desktop/src/java/security/KeyFactory.java
    /Users/yutaka/Desktop/src/java/security/KeyPairGenerator.java
    /Users/yutaka/Desktop/src/java/security/KeyStore.java
    /Users/yutaka/Desktop/src/java/security/PermissionCollection.java
    /Users/yutaka/Desktop/src/java/security/Permissions.java
    /Users/yutaka/Desktop/src/java/security/Provider.java
    /Users/yutaka/Desktop/src/java/security/SecureRandom.java
    /Users/yutaka/Desktop/src/java/security/Timestamp.java
    /Users/yutaka/Desktop/src/java/security/UnresolvedPermission.java
    /Users/yutaka/Desktop/src/java/security/UnresolvedPermissionCollection.java
    /Users/yutaka/Desktop/src/java/sql/DriverManager.java
    /Users/yutaka/Desktop/src/java/sql/SQLException.java
    /Users/yutaka/Desktop/src/java/text/DateFormatSymbols.java
    /Users/yutaka/Desktop/src/java/text/DecimalFormat.java
    /Users/yutaka/Desktop/src/java/text/DecimalFormatSymbols.java
    /Users/yutaka/Desktop/src/java/text/MergeCollation.java
    /Users/yutaka/Desktop/src/java/text/RuleBasedCollator.java
    /Users/yutaka/Desktop/src/java/text/SimpleDateFormat.java
    /Users/yutaka/Desktop/src/java/time/chrono/ChronoLocalDateTimeImpl.java
    /Users/yutaka/Desktop/src/java/time/chrono/ChronoZonedDateTimeImpl.java
    /Users/yutaka/Desktop/src/java/time/chrono/HijrahChronology.java
    /Users/yutaka/Desktop/src/java/time/chrono/HijrahDate.java
    /Users/yutaka/Desktop/src/java/time/chrono/JapaneseDate.java
    /Users/yutaka/Desktop/src/java/time/chrono/JapaneseEra.java
    /Users/yutaka/Desktop/src/java/time/chrono/MinguoDate.java
    /Users/yutaka/Desktop/src/java/time/chrono/ThaiBuddhistDate.java
    /Users/yutaka/Desktop/src/java/time/format/DateTimeFormatterBuilder.java
    /Users/yutaka/Desktop/src/java/time/temporal/JulianFields.java
    /Users/yutaka/Desktop/src/java/time/temporal/WeekFields.java
    /Users/yutaka/Desktop/src/java/time/zone/ZoneRules.java
    /Users/yutaka/Desktop/src/java/time/ZoneOffset.java
    /Users/yutaka/Desktop/src/java/time/ZoneRegion.java
    /Users/yutaka/Desktop/src/java/util/AbstractList.java
    /Users/yutaka/Desktop/src/java/util/AbstractMap.java
    /Users/yutaka/Desktop/src/java/util/ArrayDeque.java
    /Users/yutaka/Desktop/src/java/util/ArrayList.java
    /Users/yutaka/Desktop/src/java/util/BitSet.java
    /Users/yutaka/Desktop/src/java/util/Calendar.java
    /Users/yutaka/Desktop/src/java/util/Collections.java
    /Users/yutaka/Desktop/src/java/util/concurrent/ArrayBlockingQueue.java
    /Users/yutaka/Desktop/src/java/util/concurrent/atomic/AtomicBoolean.java
    /Users/yutaka/Desktop/src/java/util/concurrent/atomic/AtomicInteger.java
    /Users/yutaka/Desktop/src/java/util/concurrent/atomic/AtomicIntegerFieldUpdater.java
    /Users/yutaka/Desktop/src/java/util/concurrent/atomic/AtomicLong.java
    /Users/yutaka/Desktop/src/java/util/concurrent/atomic/AtomicLongFieldUpdater.java
    /Users/yutaka/Desktop/src/java/util/concurrent/atomic/AtomicMarkableReference.java
    /Users/yutaka/Desktop/src/java/util/concurrent/atomic/AtomicReference.java
    /Users/yutaka/Desktop/src/java/util/concurrent/atomic/AtomicReferenceFieldUpdater.java
    /Users/yutaka/Desktop/src/java/util/concurrent/atomic/AtomicStampedReference.java
    /Users/yutaka/Desktop/src/java/util/concurrent/atomic/package-info.java
    /Users/yutaka/Desktop/src/java/util/concurrent/atomic/Striped64.java
    /Users/yutaka/Desktop/src/java/util/concurrent/CompletableFuture.java
    /Users/yutaka/Desktop/src/java/util/concurrent/ConcurrentHashMap.java
    /Users/yutaka/Desktop/src/java/util/concurrent/ConcurrentLinkedDeque.java
    /Users/yutaka/Desktop/src/java/util/concurrent/ConcurrentLinkedQueue.java
    /Users/yutaka/Desktop/src/java/util/concurrent/ConcurrentSkipListMap.java
    /Users/yutaka/Desktop/src/java/util/concurrent/CopyOnWriteArrayList.java
    /Users/yutaka/Desktop/src/java/util/concurrent/CountedCompleter.java
    /Users/yutaka/Desktop/src/java/util/concurrent/DelayQueue.java
    /Users/yutaka/Desktop/src/java/util/concurrent/Exchanger.java
    /Users/yutaka/Desktop/src/java/util/concurrent/ExecutorCompletionService.java
    /Users/yutaka/Desktop/src/java/util/concurrent/ForkJoinPool.java
    /Users/yutaka/Desktop/src/java/util/concurrent/ForkJoinTask.java
    /Users/yutaka/Desktop/src/java/util/concurrent/FutureTask.java
    /Users/yutaka/Desktop/src/java/util/concurrent/LinkedBlockingDeque.java
    /Users/yutaka/Desktop/src/java/util/concurrent/LinkedBlockingQueue.java
    /Users/yutaka/Desktop/src/java/util/concurrent/LinkedTransferQueue.java
    /Users/yutaka/Desktop/src/java/util/concurrent/locks/AbstractOwnableSynchronizer.java
    /Users/yutaka/Desktop/src/java/util/concurrent/locks/AbstractQueuedLongSynchronizer.java
    /Users/yutaka/Desktop/src/java/util/concurrent/locks/AbstractQueuedSynchronizer.java
    /Users/yutaka/Desktop/src/java/util/concurrent/locks/LockSupport.java
    /Users/yutaka/Desktop/src/java/util/concurrent/locks/ReentrantReadWriteLock.java
    /Users/yutaka/Desktop/src/java/util/concurrent/locks/StampedLock.java
    /Users/yutaka/Desktop/src/java/util/concurrent/package-info.java
    /Users/yutaka/Desktop/src/java/util/concurrent/Phaser.java
    /Users/yutaka/Desktop/src/java/util/concurrent/PriorityBlockingQueue.java
    /Users/yutaka/Desktop/src/java/util/concurrent/ScheduledThreadPoolExecutor.java
    /Users/yutaka/Desktop/src/java/util/concurrent/SynchronousQueue.java
    /Users/yutaka/Desktop/src/java/util/concurrent/ThreadLocalRandom.java
    /Users/yutaka/Desktop/src/java/util/concurrent/ThreadPoolExecutor.java
    /Users/yutaka/Desktop/src/java/util/Currency.java
    /Users/yutaka/Desktop/src/java/util/Date.java
    /Users/yutaka/Desktop/src/java/util/EnumMap.java
    /Users/yutaka/Desktop/src/java/util/EventObject.java
    /Users/yutaka/Desktop/src/java/util/GregorianCalendar.java
    /Users/yutaka/Desktop/src/java/util/HashMap.java
    /Users/yutaka/Desktop/src/java/util/HashSet.java
    /Users/yutaka/Desktop/src/java/util/Hashtable.java
    /Users/yutaka/Desktop/src/java/util/IdentityHashMap.java
    /Users/yutaka/Desktop/src/java/util/JapaneseImperialCalendar.java
    /Users/yutaka/Desktop/src/java/util/jar/JarFile.java
    /Users/yutaka/Desktop/src/java/util/jar/JarVerifier.java
    /Users/yutaka/Desktop/src/java/util/LinkedHashMap.java
    /Users/yutaka/Desktop/src/java/util/LinkedList.java
    /Users/yutaka/Desktop/src/java/util/Locale.java
    /Users/yutaka/Desktop/src/java/util/logging/Handler.java
    /Users/yutaka/Desktop/src/java/util/logging/Level.java
    /Users/yutaka/Desktop/src/java/util/logging/Logger.java
    /Users/yutaka/Desktop/src/java/util/logging/LogManager.java
    /Users/yutaka/Desktop/src/java/util/logging/LogRecord.java
    /Users/yutaka/Desktop/src/java/util/logging/MemoryHandler.java
    /Users/yutaka/Desktop/src/java/util/logging/StreamHandler.java
    /Users/yutaka/Desktop/src/java/util/PriorityQueue.java
    /Users/yutaka/Desktop/src/java/util/PropertyPermission.java
    /Users/yutaka/Desktop/src/java/util/regex/Pattern.java
    /Users/yutaka/Desktop/src/java/util/ResourceBundle.java
    /Users/yutaka/Desktop/src/java/util/Scanner.java
    /Users/yutaka/Desktop/src/java/util/SimpleTimeZone.java
    /Users/yutaka/Desktop/src/java/util/stream/AbstractShortCircuitTask.java
    /Users/yutaka/Desktop/src/java/util/stream/SliceOps.java
    /Users/yutaka/Desktop/src/java/util/TimeZone.java
    /Users/yutaka/Desktop/src/java/util/TreeMap.java
    /Users/yutaka/Desktop/src/java/util/TreeSet.java
    /Users/yutaka/Desktop/src/java/util/WeakHashMap.java
    /Users/yutaka/Desktop/src/java/util/zip/ZipFile.java
    /Users/yutaka/Desktop/src/javax/accessibility/AccessibleContext.java
    /Users/yutaka/Desktop/src/javax/accessibility/AccessibleResourceBundle.java
    /Users/yutaka/Desktop/src/javax/accessibility/AccessibleState.java
    /Users/yutaka/Desktop/src/javax/lang/model/element/Modifier.java
    /Users/yutaka/Desktop/src/javax/lang/model/element/UnknownAnnotationValueException.java
    /Users/yutaka/Desktop/src/javax/lang/model/element/UnknownElementException.java
    /Users/yutaka/Desktop/src/javax/lang/model/SourceVersion.java
    /Users/yutaka/Desktop/src/javax/lang/model/type/MirroredTypeException.java
    /Users/yutaka/Desktop/src/javax/lang/model/type/MirroredTypesException.java
    /Users/yutaka/Desktop/src/javax/lang/model/type/UnknownTypeException.java
    /Users/yutaka/Desktop/src/javax/management/AttributeList.java
    /Users/yutaka/Desktop/src/javax/management/ImmutableDescriptor.java
    /Users/yutaka/Desktop/src/javax/management/loading/MLet.java
    /Users/yutaka/Desktop/src/javax/management/MBeanConstructorInfo.java
    /Users/yutaka/Desktop/src/javax/management/MBeanFeatureInfo.java
    /Users/yutaka/Desktop/src/javax/management/MBeanInfo.java
    /Users/yutaka/Desktop/src/javax/management/MBeanNotificationInfo.java
    /Users/yutaka/Desktop/src/javax/management/MBeanOperationInfo.java
    /Users/yutaka/Desktop/src/javax/management/MBeanPermission.java
    /Users/yutaka/Desktop/src/javax/management/MBeanServerPermission.java
    /Users/yutaka/Desktop/src/javax/management/modelmbean/DescriptorSupport.java
    /Users/yutaka/Desktop/src/javax/management/modelmbean/RequiredModelMBean.java
    /Users/yutaka/Desktop/src/javax/management/monitor/Monitor.java
    /Users/yutaka/Desktop/src/javax/management/Notification.java
    /Users/yutaka/Desktop/src/javax/management/ObjectName.java
    /Users/yutaka/Desktop/src/javax/management/openmbean/ArrayType.java
    /Users/yutaka/Desktop/src/javax/management/openmbean/CompositeType.java
    /Users/yutaka/Desktop/src/javax/management/openmbean/OpenMBeanAttributeInfoSupport.java
    /Users/yutaka/Desktop/src/javax/management/openmbean/OpenMBeanConstructorInfoSupport.java
    /Users/yutaka/Desktop/src/javax/management/openmbean/OpenMBeanInfoSupport.java
    /Users/yutaka/Desktop/src/javax/management/openmbean/OpenMBeanOperationInfoSupport.java
    /Users/yutaka/Desktop/src/javax/management/openmbean/OpenMBeanParameterInfoSupport.java
    /Users/yutaka/Desktop/src/javax/management/openmbean/OpenType.java
    /Users/yutaka/Desktop/src/javax/management/openmbean/SimpleType.java
    /Users/yutaka/Desktop/src/javax/management/openmbean/TabularDataSupport.java
    /Users/yutaka/Desktop/src/javax/management/openmbean/TabularType.java
    /Users/yutaka/Desktop/src/javax/management/relation/RoleList.java
    /Users/yutaka/Desktop/src/javax/management/relation/RoleUnresolvedList.java
    /Users/yutaka/Desktop/src/javax/management/remote/JMXServiceURL.java
    /Users/yutaka/Desktop/src/javax/management/remote/rmi/RMIConnector.java
    /Users/yutaka/Desktop/src/javax/management/StandardMBean.java
    /Users/yutaka/Desktop/src/javax/management/timer/Timer.java
    /Users/yutaka/Desktop/src/javax/naming/CompositeName.java
    /Users/yutaka/Desktop/src/javax/naming/CompoundName.java
    /Users/yutaka/Desktop/src/javax/naming/directory/BasicAttribute.java
    /Users/yutaka/Desktop/src/javax/naming/directory/BasicAttributes.java
    /Users/yutaka/Desktop/src/javax/naming/ldap/LdapName.java
    /Users/yutaka/Desktop/src/javax/naming/ldap/Rdn.java
    /Users/yutaka/Desktop/src/javax/print/attribute/HashAttributeSet.java
    /Users/yutaka/Desktop/src/javax/print/DocFlavor.java
    /Users/yutaka/Desktop/src/javax/print/event/PrintJobEvent.java
    /Users/yutaka/Desktop/src/javax/print/MimeType.java
    /Users/yutaka/Desktop/src/javax/rmi/CORBA/Stub.java
    /Users/yutaka/Desktop/src/javax/security/auth/kerberos/DelegationPermission.java
    /Users/yutaka/Desktop/src/javax/security/auth/kerberos/KerberosKey.java
    /Users/yutaka/Desktop/src/javax/security/auth/kerberos/KerberosPrincipal.java
    /Users/yutaka/Desktop/src/javax/security/auth/kerberos/KerberosTicket.java
    /Users/yutaka/Desktop/src/javax/security/auth/kerberos/KeyImpl.java
    /Users/yutaka/Desktop/src/javax/security/auth/kerberos/ServicePermission.java
    /Users/yutaka/Desktop/src/javax/security/auth/PrivateCredentialPermission.java
    /Users/yutaka/Desktop/src/javax/security/auth/Subject.java
    /Users/yutaka/Desktop/src/javax/security/auth/x500/X500Principal.java
    /Users/yutaka/Desktop/src/javax/sql/rowset/BaseRowSet.java
    /Users/yutaka/Desktop/src/javax/sql/rowset/serial/SerialJavaObject.java
    /Users/yutaka/Desktop/src/javax/sql/rowset/spi/SyncFactory.java
    /Users/yutaka/Desktop/src/javax/swing/AbstractAction.java
    /Users/yutaka/Desktop/src/javax/swing/AbstractButton.java
    /Users/yutaka/Desktop/src/javax/swing/AbstractCellEditor.java
    /Users/yutaka/Desktop/src/javax/swing/AbstractSpinnerModel.java
    /Users/yutaka/Desktop/src/javax/swing/ActionMap.java
    /Users/yutaka/Desktop/src/javax/swing/ActionPropertyChangeListener.java
    /Users/yutaka/Desktop/src/javax/swing/AncestorNotifier.java
    /Users/yutaka/Desktop/src/javax/swing/BoxLayout.java
    /Users/yutaka/Desktop/src/javax/swing/colorchooser/DefaultColorSelectionModel.java
    /Users/yutaka/Desktop/src/javax/swing/DefaultBoundedRangeModel.java
    /Users/yutaka/Desktop/src/javax/swing/DefaultButtonModel.java
    /Users/yutaka/Desktop/src/javax/swing/DefaultDesktopManager.java
    /Users/yutaka/Desktop/src/javax/swing/DefaultSingleSelectionModel.java
    /Users/yutaka/Desktop/src/javax/swing/event/EventListenerList.java
    /Users/yutaka/Desktop/src/javax/swing/ImageIcon.java
    /Users/yutaka/Desktop/src/javax/swing/InputMap.java
    /Users/yutaka/Desktop/src/javax/swing/JComponent.java
    /Users/yutaka/Desktop/src/javax/swing/JDesktopPane.java
    /Users/yutaka/Desktop/src/javax/swing/JFileChooser.java
    /Users/yutaka/Desktop/src/javax/swing/JLayer.java
    /Users/yutaka/Desktop/src/javax/swing/JList.java
    /Users/yutaka/Desktop/src/javax/swing/JMenuBar.java
    /Users/yutaka/Desktop/src/javax/swing/JOptionPane.java
    /Users/yutaka/Desktop/src/javax/swing/JPopupMenu.java
    /Users/yutaka/Desktop/src/javax/swing/JProgressBar.java
    /Users/yutaka/Desktop/src/javax/swing/JSlider.java
    /Users/yutaka/Desktop/src/javax/swing/JSpinner.java
    /Users/yutaka/Desktop/src/javax/swing/JTabbedPane.java
    /Users/yutaka/Desktop/src/javax/swing/JTable.java
    /Users/yutaka/Desktop/src/javax/swing/JTree.java
    /Users/yutaka/Desktop/src/javax/swing/JViewport.java
    /Users/yutaka/Desktop/src/javax/swing/LegacyGlueFocusTraversalPolicy.java
    /Users/yutaka/Desktop/src/javax/swing/MenuSelectionManager.java
    /Users/yutaka/Desktop/src/javax/swing/plaf/basic/BasicLookAndFeel.java
    /Users/yutaka/Desktop/src/javax/swing/plaf/basic/BasicPopupMenuUI.java
    /Users/yutaka/Desktop/src/javax/swing/plaf/basic/BasicScrollBarUI.java
    /Users/yutaka/Desktop/src/javax/swing/plaf/basic/BasicSliderUI.java
    /Users/yutaka/Desktop/src/javax/swing/plaf/basic/BasicTabbedPaneUI.java
    /Users/yutaka/Desktop/src/javax/swing/plaf/basic/BasicTextUI.java
    /Users/yutaka/Desktop/src/javax/swing/plaf/basic/BasicTreeUI.java
    /Users/yutaka/Desktop/src/javax/swing/plaf/basic/LazyActionMap.java
    /Users/yutaka/Desktop/src/javax/swing/plaf/metal/MetalBumps.java
    /Users/yutaka/Desktop/src/javax/swing/plaf/metal/MetalIconFactory.java
    /Users/yutaka/Desktop/src/javax/swing/plaf/nimbus/AbstractRegionPainter.java
    /Users/yutaka/Desktop/src/javax/swing/plaf/synth/SynthContext.java
    /Users/yutaka/Desktop/src/javax/swing/plaf/synth/SynthSliderUI.java
    /Users/yutaka/Desktop/src/javax/swing/Popup.java
    /Users/yutaka/Desktop/src/javax/swing/RepaintManager.java
    /Users/yutaka/Desktop/src/javax/swing/SortingFocusTraversalPolicy.java
    /Users/yutaka/Desktop/src/javax/swing/SwingWorker.java
    /Users/yutaka/Desktop/src/javax/swing/table/DefaultTableColumnModel.java
    /Users/yutaka/Desktop/src/javax/swing/table/JTableHeader.java
    /Users/yutaka/Desktop/src/javax/swing/table/TableColumn.java
    /Users/yutaka/Desktop/src/javax/swing/text/AbstractDocument.java
    /Users/yutaka/Desktop/src/javax/swing/text/DefaultCaret.java
    /Users/yutaka/Desktop/src/javax/swing/text/DefaultFormatter.java
    /Users/yutaka/Desktop/src/javax/swing/text/DefaultStyledDocument.java
    /Users/yutaka/Desktop/src/javax/swing/text/GapContent.java
    /Users/yutaka/Desktop/src/javax/swing/text/html/CSS.java
    /Users/yutaka/Desktop/src/javax/swing/text/html/HTMLEditorKit.java
    /Users/yutaka/Desktop/src/javax/swing/text/InternationalFormatter.java
    /Users/yutaka/Desktop/src/javax/swing/text/JTextComponent.java
    /Users/yutaka/Desktop/src/javax/swing/text/MaskFormatter.java
    /Users/yutaka/Desktop/src/javax/swing/text/PlainDocument.java
    /Users/yutaka/Desktop/src/javax/swing/text/SimpleAttributeSet.java
    /Users/yutaka/Desktop/src/javax/swing/text/StringContent.java
    /Users/yutaka/Desktop/src/javax/swing/text/StyleContext.java
    /Users/yutaka/Desktop/src/javax/swing/Timer.java
    /Users/yutaka/Desktop/src/javax/swing/TimerQueue.java
    /Users/yutaka/Desktop/src/javax/swing/ToolTipManager.java
    /Users/yutaka/Desktop/src/javax/swing/tree/DefaultMutableTreeNode.java
    /Users/yutaka/Desktop/src/javax/swing/tree/DefaultTreeCellEditor.java
    /Users/yutaka/Desktop/src/javax/swing/tree/DefaultTreeCellRenderer.java
    /Users/yutaka/Desktop/src/javax/swing/tree/DefaultTreeSelectionModel.java
    /Users/yutaka/Desktop/src/javax/xml/bind/annotation/XmlAccessType.java
    /Users/yutaka/Desktop/src/javax/xml/bind/annotation/XmlAnyAttribute.java
    /Users/yutaka/Desktop/src/javax/xml/bind/annotation/XmlElement.java
    /Users/yutaka/Desktop/src/javax/xml/bind/annotation/XmlElements.java
    /Users/yutaka/Desktop/src/javax/xml/bind/annotation/XmlElementWrapper.java
    /Users/yutaka/Desktop/src/javax/xml/bind/annotation/XmlID.java
    /Users/yutaka/Desktop/src/javax/xml/bind/annotation/XmlIDREF.java
    /Users/yutaka/Desktop/src/javax/xml/bind/annotation/XmlType.java
    /Users/yutaka/Desktop/src/javax/xml/bind/annotation/XmlValue.java
    /Users/yutaka/Desktop/src/javax/xml/bind/DatatypeConverter.java
    /Users/yutaka/Desktop/src/javax/xml/bind/JAXB.java
    /Users/yutaka/Desktop/src/javax/xml/bind/JAXBException.java
    /Users/yutaka/Desktop/src/javax/xml/bind/TypeConstraintException.java
    /Users/yutaka/Desktop/src/javax/xml/datatype/FactoryFinder.java
    /Users/yutaka/Desktop/src/javax/xml/parsers/FactoryFinder.java
    /Users/yutaka/Desktop/src/javax/xml/stream/events/XMLEvent.java
    /Users/yutaka/Desktop/src/javax/xml/stream/FactoryFinder.java
    /Users/yutaka/Desktop/src/javax/xml/stream/XMLStreamReader.java
    /Users/yutaka/Desktop/src/javax/xml/transform/FactoryFinder.java
    /Users/yutaka/Desktop/src/javax/xml/validation/SchemaFactoryFinder.java
    /Users/yutaka/Desktop/src/javax/xml/xpath/XPathFactoryFinder.java
    /Users/yutaka/Desktop/src/org/omg/CORBA/portable/ObjectImpl.java
    /Users/yutaka/Desktop/src/org/omg/PortableServer/POAOperations.java
    /Users/yutaka/Desktop/src/org/omg/PortableServer/Servant.java
    */

}
